### ISSUE TITLE
arm dockerfile

### ISSUE THREAD

**Issue by FernandoMiguel** [naorlivne/terraformize#3]
I'm not sure what your use of the arm Dockerfile is, and I don't see any ARCH anywhere.
Given terraform is a static linked Go binary, the same Dockerfile should work for both ARCH

**Comment by naorlivne** [comment]
Unfortunately that's not the case, the terrafrom go binary depends on the underlying ARCH it's built on so a Terraform bin built on amd64 won't work on arm and vice-versa (that's why https://www.terraform.io/downloads.html has a different download for arm then amd 64bit).

The reason for the different Dockerfile-arm is that it downloads the arm version of the terraform binary.

**Comment by FernandoMiguel** [comment]
I feared as much.
Sadly, I don't see a multi arch Dockerfile at dockerhub, so the same technique can't be used.

Let me see if I can nudge someone at hashi to push it there
